import { Prisma } from "@prisma/client";
import { doctorQuestionnaireDefinition } from "@/lib/questionnaire";
import { buildPromAuditPayload, computePromScore, inferPromInstrument } from "@/lib/prom-scoring";
import { prisma } from "@/lib/prisma";
import { toPlainQuestionText } from "@/lib/question-text";

export const doctorQuestionnaireSlug = "sei-doctor-consult-v1";

type DoctorAnswerValue = string | number | boolean | string[];

type DoctorQuestionnairePayload = {
  consultSessionId: string;
  answers: Record<string, DoctorAnswerValue>;
  stepIndex: number;
  submitted: boolean;
  patientName?: string;
  patientPhone?: string;
  appointmentTime?: string;
  appointmentType?: string;
  appointmentStatus?: string;
  updatedAt?: string;
};

export type DoctorQuestionnaireRecord = DoctorQuestionnairePayload & {
  source: "database";
};

export type DoctorPersistedAiSummary = {
  consultSessionId: string;
  summary: string;
  generatedAt?: string;
};

function answerValue(value: unknown) {
  return value as Prisma.InputJsonValue;
}

const doctorAuditAnswerKeys = {
  promPayload: "__doctorPromAutoAudit",
  promInstrument: "__doctorPromAutoInstrument",
  promPercent: "__doctorPromAutoPercent",
  promSeverity: "__doctorPromAutoSeverity",
  promGeneratedAt: "__doctorPromAutoGeneratedAt",
} as const;

const doctorAiSummaryAnswerKeys = {
  postConsultSummary: "__doctorAiPostConsultSummary",
  generatedAt: "__doctorAiPostConsultGeneratedAt",
} as const;

function isKnownDoctorField(key: string) {
  return doctorQuestionnaireDefinition.questions.some((question) => question.id === key);
}

function parseFiniteNumber(value: unknown) {
  if (typeof value === "number" && Number.isFinite(value)) {
    return value;
  }

  if (typeof value === "string" && value.trim().length > 0) {
    const parsed = Number(value);
    return Number.isFinite(parsed) ? parsed : null;
  }

  return null;
}

function parseBoolean(value: unknown) {
  if (typeof value === "boolean") {
    return value;
  }

  if (typeof value === "string") {
    const normalized = value.trim().toLowerCase();
    if (["true", "yes", "1"].includes(normalized)) return true;
    if (["false", "no", "0"].includes(normalized)) return false;
  }

  return null;
}

function asStringArray(value: unknown) {
  if (!Array.isArray(value)) {
    return [] as string[];
  }

  return value.map((entry) => String(entry ?? "").trim()).filter((entry) => entry.length > 0);
}

function firstDefined(answers: Record<string, unknown>, keys: string[]) {
  for (const key of keys) {
    const value = answers[key];
    if (value !== undefined && value !== null && String(value).trim() !== "") {
      return value;
    }
  }

  return undefined;
}

function hasUrgentRedFlag(answers: Record<string, unknown>) {
  return [
    "redFlagBladderBowel",
    "redFlagRapidWeakness",
    "redFlagFever",
    "redFlagTrauma",
    "redFlagCancer",
    "redFlagWeightLoss",
  ].some((key) => parseBoolean(answers[key]) === true);
}

function isDoctorAnswerEmpty(value: DoctorAnswerValue | undefined) {
  if (value === undefined || value === null) {
    return true;
  }

  if (Array.isArray(value)) {
    return value.length === 0;
  }

  if (typeof value === "string") {
    return value.trim().length === 0;
  }

  return false;
}

function mergeMissingDoctorAnswers(
  base: Record<string, DoctorAnswerValue>,
  defaults: Record<string, DoctorAnswerValue>,
) {
  const merged = { ...base };

  for (const [key, value] of Object.entries(defaults)) {
    if (isDoctorAnswerEmpty(merged[key])) {
      merged[key] = value;
    }
  }

  return merged;
}

function buildDoctorAutofillFromPatientAnswers(patientAnswers: Record<string, unknown>) {
  const result: Record<string, DoctorAnswerValue> = {};

  const primaryReason = String(patientAnswers.q1PrimaryReason ?? "").trim();
  const consultationTypeByReason: Record<string, string> = {
    "follow-up": "follow-up",
    "second-opinion": "second-opinion",
  };
  result.consultationType = consultationTypeByReason[primaryReason] ?? "first";

  const primaryProblemByReason: Record<string, string> = {
    "neck-pain": "neck-pain",
    "back-pain": "back-pain",
    "arm-pain": "arm-radiculopathy",
    "leg-pain": "leg-sciatica",
    numbness: "numbness-tingling",
    weakness: "weakness",
    "walking-difficulty": "walking-imbalance",
  };
  if (primaryProblemByReason[primaryReason]) {
    result.primaryProblem = primaryProblemByReason[primaryReason];
  }

  const q4Duration = String(patientAnswers.q4Duration ?? "").trim();
  const durationBandByQ4: Record<string, string> = {
    "lt-2wk": "lt-6-weeks",
    "2wk-3m": "6-weeks-to-3-months",
    "3m-6m": "3-to-6-months",
    "gt-6m": "gt-6-months",
  };
  if (durationBandByQ4[q4Duration]) {
    result.symptomDurationBand = durationBandByQ4[q4Duration];
  } else {
    const durationDays = parseFiniteNumber(patientAnswers.symptomDuration);
    if (durationDays !== null) {
      result.symptomDurationBand =
        durationDays < 42 ? "lt-6-weeks" : durationDays <= 90 ? "6-weeks-to-3-months" : durationDays <= 180 ? "3-to-6-months" : "gt-6-months";
    }
  }

  const weaknessValue = firstDefined(patientAnswers, ["q11Weakness", "limbWeakness"]);
  if (weaknessValue !== undefined) {
    const normalized = String(weaknessValue).trim();
    result.motorWeakness = ["none", "no"].includes(normalized) ? "no" : "present";
  }

  const numbnessValue = firstDefined(patientAnswers, ["q10Numbness"]);
  if (numbnessValue !== undefined) {
    const normalized = String(numbnessValue).trim();
    result.sensoryDeficit = normalized === "none" ? "no" : "present";
  } else {
    const numbnessToggle = parseBoolean(patientAnswers.numbnessTingling);
    if (numbnessToggle !== null) {
      result.sensoryDeficit = numbnessToggle ? "present" : "no";
    }
  }

  const bladderBowelFlag = parseBoolean(patientAnswers.redFlagBladderBowel);
  if (bladderBowelFlag !== null) {
    result.bladderBowelInvolvement = bladderBowelFlag ? "present" : "no";
  }

  const balanceValue = firstDefined(patientAnswers, ["myelopathyBalance"]);
  if (balanceValue !== undefined) {
    const normalized = String(balanceValue).trim();
    result.gaitImbalance = normalized === "normal" ? "no" : "present";
  } else {
    const walkingBalanceToggle = parseBoolean(patientAnswers.walkingBalance);
    if (walkingBalanceToggle !== null) {
      result.gaitImbalance = walkingBalanceToggle ? "present" : "no";
    }
  }

  const mriAvailability = String(patientAnswers.mriAvailability ?? "").trim();
  const reportsWithPatient = asStringArray(patientAnswers.reportsWithPatient);
  if (mriAvailability === "images-and-report" || mriAvailability === "report-only" || reportsWithPatient.includes("mri-images") || reportsWithPatient.includes("mri-report")) {
    result.imagingAvailable = "mri";
    result.mriRequiredStage = "yes";
  } else if (reportsWithPatient.includes("xray")) {
    result.imagingAvailable = "xray";
    result.mriRequiredStage = "no";
  } else if (reportsWithPatient.includes("none") || mriAvailability === "none") {
    result.imagingAvailable = "none";
    result.mriRequiredStage = "yes";
  }

  const vasPain = parseFiniteNumber(firstDefined(patientAnswers, ["q6VasPain", "painScore"]));
  if (vasPain !== null) {
    result.vasPainScore = Math.max(0, Math.min(10, Math.round(vasPain)));
  }

  const workSource = firstDefined(patientAnswers, ["ndiWork", "odiLifting", "walkingImpact"]);
  if (workSource !== undefined) {
    const normalized = String(workSource).trim();
    if (["0", "1", "30-plus"].includes(normalized)) {
      result.workLimitation = "none";
    } else if (["4", "5", "less-15"].includes(normalized)) {
      result.workLimitation = "unable";
    } else {
      result.workLimitation = "partial";
    }
  }

  const concernSource = firstDefined(patientAnswers, ["mainConcern", "redFlagReason", "medicalHistory"]);
  if (concernSource !== undefined) {
    const remark = String(concernSource).trim();
    if (remark.length > 0) {
      result.clinicalRemarks = remark;
    }
  }

  const urgentRisk = hasUrgentRedFlag(patientAnswers);
  if (urgentRisk) {
    result.overallRiskCategory = "urgent";
    result.furtherInvestigationRequired = "yes";
    result.furtherInvestigationReason = "red-flag-evaluation";
    result.physicalExamRequired = "required";
    result.physicalExamReason = "red-flag-confirmation";
    result.carePathway = "pathway-5";
  }

  return result;
}

async function getPatientDoctorAutofillAnswers(consultSessionId: string): Promise<Record<string, DoctorAnswerValue> | null> {
  if (!prisma) {
    return null;
  }

  const submission = await prisma.questionnaireSubmission.findUnique({
    where: { sessionId: consultSessionId },
    include: { answers: true },
  });

  if (!submission) {
    return null;
  }

  const patientAnswers = Object.fromEntries(
    submission.answers
      .filter((answer) => !answer.key.startsWith("__"))
      .map((answer) => [answer.key, answer.value as unknown]),
  );

  const mappedPatientDefaults = buildDoctorAutofillFromPatientAnswers(patientAnswers);

  const score = computePromScore(patientAnswers);
  if (score.percent === null) {
    return Object.keys(mappedPatientDefaults).length > 0 ? mappedPatientDefaults : null;
  }

  const roundedPercent = Math.round(score.percent * 10) / 10;
  const riskAndPathwayHints: Record<string, DoctorAnswerValue> =
    roundedPercent >= 61
      ? {
          patientRiskCategory: "high",
          aiSuggestedPathway: "priority-review",
          overallRiskCategory: "urgent",
          carePathway: "pathway-4",
        }
      : roundedPercent >= 41
        ? {
            patientRiskCategory: "high",
            aiSuggestedPathway: "specialist-evaluation",
            overallRiskCategory: "needs-follow-up",
            carePathway: "pathway-3",
          }
        : roundedPercent >= 21
          ? {
              patientRiskCategory: "moderate",
              aiSuggestedPathway: "conservative",
              overallRiskCategory: "needs-follow-up",
              carePathway: "pathway-2",
            }
          : {
              patientRiskCategory: "low",
              aiSuggestedPathway: "education",
              overallRiskCategory: "routine",
              carePathway: "pathway-1",
            };

  const promDefaults =
    score.instrument === "NDI"
      ? {
          ndiPercent: roundedPercent,
          ...riskAndPathwayHints,
        }
      : {
          odiPercent: roundedPercent,
          ...riskAndPathwayHints,
        };

  return {
    ...mappedPatientDefaults,
    ...promDefaults,
  };
}

function normalizePhone(value: unknown) {
  return String(value ?? "").replace(/\D/g, "");
}

function normalizeEmailPart(value: string) {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "") || "user";
}

function jsonObject(value: unknown) {
  return value as Prisma.InputJsonObject;
}

function buildDoctorScore(answers: Record<string, DoctorAnswerValue>) {
  const validation = String(answers.summaryValidation ?? "").trim();

  if (validation === "clinically-accurate") {
    return 100;
  }

  if (validation === "partially-accurate") {
    return 70;
  }

  if (validation === "needs-correction") {
    return 40;
  }

  return 0;
}

function getQuestionnaireQuestionData(questionnaireId: string) {
  return doctorQuestionnaireDefinition.questions.map((question, index) => ({
    questionnaireId,
    key: question.id,
    label: toPlainQuestionText(question.label),
    type: question.type,
    helpText: question.helpText ?? null,
    sortOrder: index + 1,
    config: jsonObject({
      sectionId: question.sectionId ?? null,
      sectionTitle: question.sectionTitle ?? null,
      required: Boolean(question.required),
      options: (question.options ?? []).map((option) => ({
        ...option,
        label: toPlainQuestionText(option.label),
      })),
      multiSelect: Boolean(question.multiSelect),
      placeholder: question.placeholder ?? null,
      min: question.min ?? null,
      max: question.max ?? null,
      step: question.step ?? null,
    }),
  }));
}

type QuestionShapeRow = {
  key: string;
  label: string;
  type: string;
  helpText: string | null;
  sortOrder: number;
  config: unknown;
};

function normalizeQuestionConfig(config: unknown) {
  const source = (config ?? {}) as {
    sectionId?: string | null;
    sectionTitle?: string | null;
    required?: boolean;
    options?: Array<{ label: string; value: string }>;
    multiSelect?: boolean;
    placeholder?: string | null;
    min?: number | null;
    max?: number | null;
    step?: number | null;
  };

  return {
    sectionId: source.sectionId ?? null,
    sectionTitle: source.sectionTitle ?? null,
    required: Boolean(source.required),
    options: Array.isArray(source.options) ? source.options : [],
    multiSelect: Boolean(source.multiSelect),
    placeholder: source.placeholder ?? null,
    min: source.min ?? null,
    max: source.max ?? null,
    step: source.step ?? null,
  };
}

function hasSameQuestionShape(expected: QuestionShapeRow[], existing: QuestionShapeRow[]) {
  if (expected.length !== existing.length) {
    return false;
  }

  return expected.every((expectedRow, index) => {
    const existingRow = existing[index];
    if (!existingRow) {
      return false;
    }

    return (
      expectedRow.key === existingRow.key &&
      expectedRow.label === existingRow.label &&
      expectedRow.type === existingRow.type &&
      expectedRow.helpText === existingRow.helpText &&
      expectedRow.sortOrder === existingRow.sortOrder &&
      JSON.stringify(normalizeQuestionConfig(expectedRow.config)) ===
        JSON.stringify(normalizeQuestionConfig(existingRow.config))
    );
  });
}

async function ensureDoctorQuestionnaire() {
  if (!prisma) {
    return null;
  }

  const questionnaire = await prisma.questionnaire.upsert({
    where: { slug: doctorQuestionnaireSlug },
    create: {
      slug: doctorQuestionnaireSlug,
      title: doctorQuestionnaireDefinition.title,
      subtitle: doctorQuestionnaireDefinition.subtitle,
      version: 1,
      audience: ["doctor"],
    },
    update: {
      title: doctorQuestionnaireDefinition.title,
      subtitle: doctorQuestionnaireDefinition.subtitle,
      audience: ["doctor"],
    },
  });

    const expectedQuestionData = getQuestionnaireQuestionData(questionnaire.id);
  const existingQuestions = await prisma.questionnaireQuestion.findMany({
    where: { questionnaireId: questionnaire.id },
      select: {
        key: true,
        label: true,
        type: true,
        helpText: true,
        sortOrder: true,
        config: true,
      },
      orderBy: { sortOrder: "asc" },
  });

    const hasCurrentShape = hasSameQuestionShape(expectedQuestionData, existingQuestions);

  if (!hasCurrentShape) {
    await prisma.questionnaireQuestion.deleteMany({ where: { questionnaireId: questionnaire.id } });
      await prisma.questionnaireQuestion.createMany({ data: expectedQuestionData });
  }

  return questionnaire;
}

export async function getDoctorQuestionnaireContent() {
  if (!prisma) {
    return {
      source: "local" as const,
      definition: doctorQuestionnaireDefinition,
    };
  }

  try {
    const questionnaire = await ensureDoctorQuestionnaire();

    if (!questionnaire) {
      return {
        source: "local" as const,
        definition: doctorQuestionnaireDefinition,
      };
    }

    const questions = await prisma.questionnaireQuestion.findMany({
      where: { questionnaireId: questionnaire.id },
      orderBy: { sortOrder: "asc" },
    });

    return {
      source: "database" as const,
      definition: {
        id: doctorQuestionnaireDefinition.id,
        title: questionnaire.title,
        subtitle: questionnaire.subtitle,
        audience: ["doctor"],
        questions: questions.map((question) => {
          const config = question.config as {
            sectionId?: string;
            sectionTitle?: string;
            required?: boolean;
            options?: Array<{ label: string; value: string }>;
            multiSelect?: boolean;
            placeholder?: string;
            min?: number;
            max?: number;
            step?: number;
          };

          return {
            id: question.key,
            label: question.label,
            type: question.type,
            helpText: question.helpText ?? undefined,
              sectionId: typeof config.sectionId === "string" ? config.sectionId : undefined,
              sectionTitle: typeof config.sectionTitle === "string" ? config.sectionTitle : undefined,
            required: Boolean(config.required),
            options: Array.isArray(config.options) ? config.options : undefined,
              multiSelect: Boolean(config.multiSelect),
            placeholder: typeof config.placeholder === "string" ? config.placeholder : undefined,
            min: typeof config.min === "number" ? config.min : undefined,
            max: typeof config.max === "number" ? config.max : undefined,
            step: typeof config.step === "number" ? config.step : undefined,
          };
        }),
      },
    };
  } catch {
    return {
      source: "local" as const,
      definition: doctorQuestionnaireDefinition,
    };
  }
}

export async function getSavedDoctorQuestionnaire(input: { consultSessionId?: string }) {
  if (!prisma || !input.consultSessionId) {
    return null;
  }

  const submissionSessionId = `${input.consultSessionId}:doctor`;

  try {
    const submission = await prisma.questionnaireSubmission.findUnique({
      where: { sessionId: submissionSessionId },
      include: { answers: true },
    });

    if (!submission) {
      const autoAnswers = await getPatientDoctorAutofillAnswers(input.consultSessionId);
      if (!autoAnswers) {
        return null;
      }

      return {
        source: "database" as const,
        consultSessionId: input.consultSessionId,
        answers: autoAnswers,
        stepIndex: 0,
        submitted: false,
        updatedAt: new Date().toISOString(),
        score: null,
      };
    }

    return {
      source: "database" as const,
      consultSessionId: input.consultSessionId,
      answers: Object.fromEntries(
        submission.answers
          .filter((answer) => isKnownDoctorField(answer.key))
          .map((answer) => [answer.key, answer.value as DoctorAnswerValue]),
      ),
      stepIndex: submission.questionIndex,
      submitted: submission.status === "submitted",
      updatedAt: submission.updatedAt.toISOString(),
      score: submission.answers.find((answer) => answer.key === "doctorScore")?.value ?? null,
    };
  } catch {
    return null;
  }
}

export async function saveDoctorQuestionnaireToDatabase(record: DoctorQuestionnairePayload) {
  const database = prisma;

  if (!database) {
    return { ok: true as const, storage: "local" as const, persisted: false };
  }

  const questionnaire = await ensureDoctorQuestionnaire();
  if (!questionnaire) {
    return { ok: true as const, storage: "local" as const, persisted: false };
  }

  const autoPrefillAnswers = await getPatientDoctorAutofillAnswers(record.consultSessionId);
  const normalizedAnswers: Record<string, DoctorAnswerValue> = { ...record.answers };
  if (autoPrefillAnswers) {
    Object.assign(normalizedAnswers, mergeMissingDoctorAnswers(normalizedAnswers, autoPrefillAnswers));
  }

  const status = record.submitted ? "submitted" : "draft";
  const totalQuestions = Math.max(1, doctorQuestionnaireDefinition.questions.length);
  const answeredCount = Object.values(normalizedAnswers).filter((value) => {
    if (Array.isArray(value)) return value.length > 0;
    if (typeof value === "string") return value.trim().length > 0;
    return value !== undefined && value !== null;
  }).length;
  const completionPct = Math.min(100, Math.round((answeredCount / totalQuestions) * 100));
  const doctorScore = buildDoctorScore(normalizedAnswers);
  const submissionSessionId = `${record.consultSessionId}:doctor`;

  const inferredInstrument = inferPromInstrument(normalizedAnswers as Record<string, unknown>);
  const promAudit = buildPromAuditPayload(normalizedAnswers as Record<string, unknown>);
  const doctorEnteredPercent = parseFiniteNumber(
    inferredInstrument === "NDI" ? normalizedAnswers.ndiPercent : normalizedAnswers.odiPercent,
  );
  const resolvedPercent = doctorEnteredPercent ?? promAudit.percent;
  const resolvedSeverity =
    resolvedPercent === null
      ? "Not enough data"
      : inferredInstrument === "NDI"
        ? computePromScore({ ...normalizedAnswers, q1PrimaryReason: "neck-pain" } as Record<string, unknown>).severity
        : computePromScore({ ...normalizedAnswers, q1PrimaryReason: "back-pain" } as Record<string, unknown>).severity;

  const saved = await database.$transaction(async (tx) => {
    let appointment = await tx.appointment.findFirst({
      where: {
        OR: [{ consultSessionId: record.consultSessionId }, { id: record.consultSessionId }],
      },
      orderBy: { updatedAt: "desc" },
    });

    if (!appointment) {
      const normalizedPhone = normalizePhone(record.patientPhone || record.consultSessionId);
      const patientDisplayName = String(record.patientName || "Patient").trim() || "Patient";
      const patientEmail = `patient-${normalizedPhone || normalizeEmailPart(record.consultSessionId)}@spinexpert.local`;

      const patientUser = await tx.user.upsert({
        where: { email: patientEmail },
        create: {
          email: patientEmail,
          passwordHash: `patient:${normalizedPhone || record.consultSessionId}`,
          role: "patient",
          displayName: patientDisplayName,
        },
        update: {
          displayName: patientDisplayName,
        },
      });

      const existingDoctor = await tx.doctorProfile.findFirst({
        include: { user: true },
        orderBy: { createdAt: "asc" },
      });

      const doctorUser = existingDoctor
        ? existingDoctor.user
        : await tx.user.upsert({
            where: { email: "doctor-auto-assigned@spinexpert.local" },
            create: {
              email: "doctor-auto-assigned@spinexpert.local",
              passwordHash: "doctor:auto-assigned",
              role: "doctor",
              displayName: "Assigned SpinExpert doctor",
              doctorProfile: {
                create: {
                  name: "Assigned SpinExpert doctor",
                  phone: "not-provided",
                  registrationNumber: "auto-assigned",
                  licenseNumber: "auto-assigned",
                  bio: "",
                },
              },
            },
            update: {
              displayName: "Assigned SpinExpert doctor",
            },
          });

      const appointmentDate = new Date();
      appointment = await tx.appointment.upsert({
        where: { consultSessionId: record.consultSessionId },
        create: {
          consultSessionId: record.consultSessionId,
          patientId: patientUser.id,
          patientName: patientDisplayName,
          patientPhone: normalizedPhone,
          doctorId: doctorUser.id,
          doctorName: doctorUser.displayName,
          appointmentDate,
          appointmentTime: String(record.appointmentTime || "09:00"),
          appointmentType: String(record.appointmentType || "questionnaire"),
          status: "submitted",
          createdBy: "doctor",
          notes: "Auto-created for doctor questionnaire submission",
        } as never,
        update: {
          patientName: patientDisplayName,
          patientPhone: normalizedPhone,
          appointmentTime: String(record.appointmentTime || "09:00"),
          appointmentType: String(record.appointmentType || "questionnaire"),
          status: String(record.appointmentStatus || "submitted"),
          updatedAt: appointmentDate,
        } as never,
      });
    }

    const submission = await tx.questionnaireSubmission.upsert({
      where: { sessionId: submissionSessionId },
      create: {
        questionnaireId: questionnaire.id,
        appointmentId: appointment.id,
        patientId: appointment.patientId,
        doctorId: appointment.doctorId,
        sessionId: submissionSessionId,
        patientPhone: appointment.patientPhone || null,
        status,
        sectionIndex: 0,
        questionIndex: record.stepIndex,
        completionPct,
        durationSeconds: 0,
        bmi: null,
      },
      update: {
        status,
        questionIndex: record.stepIndex,
        completionPct,
      },
      select: {
        id: true,
        createdAt: true,
      },
    });

    const durationSeconds = Math.max(0, Math.round((Date.now() - submission.createdAt.getTime()) / 1000));
    await tx.questionnaireSubmission.update({
      where: { id: submission.id },
      data: { durationSeconds },
      select: { id: true },
    });

    await tx.questionnaireAnswer.deleteMany({ where: { submissionId: submission.id } });
    await tx.questionnaireAnswer.createMany({
      data: [
        ...Object.entries(normalizedAnswers).map(([key, value]) => ({
          submissionId: submission.id,
          key,
          value: answerValue(value),
        })),
        {
          submissionId: submission.id,
          key: "doctorScore",
          value: answerValue(doctorScore),
        },
        {
          submissionId: submission.id,
          key: doctorAuditAnswerKeys.promPayload,
          value: answerValue(promAudit as unknown as DoctorAnswerValue),
        },
        {
          submissionId: submission.id,
          key: doctorAuditAnswerKeys.promInstrument,
          value: answerValue(inferredInstrument),
        },
        {
          submissionId: submission.id,
          key: doctorAuditAnswerKeys.promPercent,
          value: answerValue(resolvedPercent ?? ""),
        },
        {
          submissionId: submission.id,
          key: doctorAuditAnswerKeys.promSeverity,
          value: answerValue(resolvedSeverity),
        },
        {
          submissionId: submission.id,
          key: doctorAuditAnswerKeys.promGeneratedAt,
          value: answerValue(new Date().toISOString()),
        },
      ],
    });

    return { submissionId: submission.id, score: doctorScore };
  });

  return {
    ok: true as const,
    storage: "database" as const,
    persisted: true,
    submissionId: saved.submissionId,
    score: saved.score,
  };
}

export async function getSavedDoctorPostConsultSummary(input: {
  consultSessionId?: string;
}): Promise<DoctorPersistedAiSummary | null> {
  if (!prisma || !input.consultSessionId) {
    return null;
  }

  const submissionSessionId = `${input.consultSessionId}:doctor`;
  const submission = await prisma.questionnaireSubmission.findUnique({
    where: { sessionId: submissionSessionId },
    include: { answers: true },
  });

  if (!submission) {
    return null;
  }

  const summary = submission.answers.find((answer) => answer.key === doctorAiSummaryAnswerKeys.postConsultSummary)?.value;
  if (typeof summary !== "string" || summary.trim().length === 0) {
    return null;
  }

  const generatedAtValue = submission.answers.find((answer) => answer.key === doctorAiSummaryAnswerKeys.generatedAt)?.value;
  const generatedAt = typeof generatedAtValue === "string" && generatedAtValue.trim().length > 0 ? generatedAtValue : undefined;

  return {
    consultSessionId: input.consultSessionId,
    summary,
    generatedAt,
  };
}

export async function saveDoctorPostConsultSummary(input: {
  consultSessionId: string;
  summary: string;
  generatedAt?: string;
}) {
  if (!prisma) {
    return { ok: true as const, storage: "local" as const, persisted: false };
  }

  const submissionSessionId = `${input.consultSessionId}:doctor`;
  const submission = await prisma.questionnaireSubmission.findUnique({
    where: { sessionId: submissionSessionId },
    select: { id: true },
  });

  if (!submission) {
    return {
      ok: false as const,
      message: "Doctor consultation record not found for this visit",
      storage: "database" as const,
      persisted: false,
    };
  }

  const generatedAt = typeof input.generatedAt === "string" && input.generatedAt.trim().length > 0
    ? input.generatedAt
    : new Date().toISOString();

  await prisma.$transaction(async (tx) => {
    await tx.questionnaireAnswer.deleteMany({
      where: {
        submissionId: submission.id,
        key: {
          in: [doctorAiSummaryAnswerKeys.postConsultSummary, doctorAiSummaryAnswerKeys.generatedAt],
        },
      },
    });

    await tx.questionnaireAnswer.createMany({
      data: [
        {
          submissionId: submission.id,
          key: doctorAiSummaryAnswerKeys.postConsultSummary,
          value: answerValue(input.summary),
        },
        {
          submissionId: submission.id,
          key: doctorAiSummaryAnswerKeys.generatedAt,
          value: answerValue(generatedAt),
        },
      ],
    });
  });

  return {
    ok: true as const,
    storage: "database" as const,
    persisted: true,
    generatedAt,
  };
}
