import { Prisma } from "@prisma/client";
import { calculateBmi } from "@/lib/questionnaire";
import { buildPromAuditPayload } from "@/lib/prom-scoring";
import { prisma } from "@/lib/prisma";
import { toPlainQuestionText } from "@/lib/question-text";
import { ensurePatientRecordForPhone } from "@/lib/patient-record";
import { patientWorkflowSections, preConsultSections, type WorkflowSection } from "@/lib/workflow-data";

export const patientQuestionnaireSlug = "sei-pq-v3-final";

type PatientAnswerValue = string | number | boolean | string[];

type PatientQuestionnairePayload = {
  sessionId: string;
  patientPhone?: string;
  answers: Record<string, PatientAnswerValue>;
  sectionIndex: number;
  questionIndex: number;
  submitted: boolean;
  updatedAt?: string;
};

export type PatientQuestionnaireRecord = PatientQuestionnairePayload & {
  source: "database";
};

export type PatientQuestionContent = {
  id: string;
  label: string;
  type: string;
  helpText?: string;
  required?: boolean;
  options?: Array<{ label: string; value: string }>;
};

function normalizePhone(value: unknown) {
  return String(value ?? "").replace(/\D/g, "");
}

function normalizeEmailPart(value: string) {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "") || "user";
}

function asNumber(value: unknown) {
  const parsed = Number(value);
  return Number.isFinite(parsed) && parsed > 0 ? parsed : null;
}

function asString(value: unknown) {
  const parsed = String(value ?? "").trim();
  return parsed.length > 0 ? parsed : null;
}

function asStringArray(value: unknown) {
  if (!Array.isArray(value)) {
    return [] as string[];
  }

  return value
    .map((item) => String(item ?? "").trim())
    .filter((item) => item.length > 0);
}

function buildPatientId() {
  const year = new Date().getFullYear();
  const randomPart = String(Math.floor(Math.random() * 100000)).padStart(5, "0");
  return `PT-${year}-${randomPart}`;
}

function jsonObject(value: unknown) {
  return value as Prisma.InputJsonObject;
}

function answerValue(value: unknown) {
  return value as Prisma.InputJsonValue;
}

const promAuditAnswerKeys = {
  payload: "__promAutoAudit",
  instrument: "__promAutoInstrument",
  percent: "__promAutoPercent",
  severity: "__promAutoSeverity",
  generatedAt: "__promAutoGeneratedAt",
} as const;

const knownAnswerKeys = new Set(
  [patientWorkflowSections, preConsultSections]
    .flatMap((sections) => sections.flatMap((section) => section.questions.map((question) => question.id))),
);

function pickWorkflowSectionsForAnswers(answers: Record<string, PatientAnswerValue>) {
  const answerKeys = new Set(Object.keys(answers));
  const sectionCandidates = [preConsultSections, patientWorkflowSections] as const;

  const withScores = sectionCandidates.map((sections) => {
    const questionKeys = new Set(sections.flatMap((section) => section.questions.map((question) => question.id)));
    let matches = 0;
    for (const key of answerKeys) {
      if (questionKeys.has(key)) {
        matches += 1;
      }
    }

    return { sections, matches };
  });

  const best = withScores.sort((a, b) => b.matches - a.matches)[0];
  return best.matches > 0 ? best.sections : patientWorkflowSections;
}

function getVisibleQuestions(sections: WorkflowSection[], answers: Record<string, PatientAnswerValue>) {
  return sections.flatMap((section) =>
    section.questions.filter((question) => !question.showIf || question.showIf(answers as Record<string, unknown>)),
  );
}

function isFilled(value: PatientAnswerValue | undefined) {
  if (Array.isArray(value)) {
    return value.length > 0;
  }

  if (typeof value === "string") {
    return value.trim().length > 0;
  }

  return value !== undefined && value !== null;
}

function getQuestionnaireQuestionData(questionnaireId: string) {
  let sortOrder = 0;

  return patientWorkflowSections.flatMap((section) =>
    section.questions.map((question) => {
      sortOrder += 1;

      return {
        questionnaireId,
        key: question.id,
        label: toPlainQuestionText(question.label),
        type: question.type,
        helpText: question.helpText ?? null,
        sortOrder,
        config: jsonObject({
          sectionId: section.id,
          sectionTitle: section.title,
          sectionSubtitle: section.subtitle,
          sectionNote: section.note ?? null,
          required: Boolean(question.required),
          options: (question.options ?? []).map((option) => ({
            ...option,
            label: toPlainQuestionText(option.label),
          })),
          linkedFrom: question.linkedFrom ?? null,
          branchOn: question.branchOn ?? null,
          branchValue: question.branchValue ?? null,
        }),
      };
    }),
  );
}

function getLocalPatientQuestionContent(): PatientQuestionContent[] {
  return patientWorkflowSections.flatMap((section) =>
    section.questions.map((question) => ({
      id: question.id,
      label: toPlainQuestionText(question.label),
      type: question.type,
      helpText: question.helpText,
      required: question.required,
      options: question.options?.map((option) => ({
        ...option,
        label: toPlainQuestionText(option.label),
      })),
    })),
  );
}

async function ensurePatientQuestionnaire() {
  if (!prisma) {
    return null;
  }

  const questionnaire = await prisma.questionnaire.upsert({
    where: { slug: patientQuestionnaireSlug },
    create: {
      slug: patientQuestionnaireSlug,
      title: "SpinExpert patient spine intake",
      subtitle: "Pre-consult spine health assessment",
      version: 3,
      audience: ["patient", "doctor"],
    },
    update: {
      title: "SpinExpert patient spine intake",
      subtitle: "Pre-consult spine health assessment",
      version: 3,
      audience: ["patient", "doctor"],
    },
  });

  const expectedKeys = patientWorkflowSections.flatMap((section) => section.questions.map((question) => question.id));
  const expectedQuestions = getQuestionnaireQuestionData(questionnaire.id);
  const expectedByKey = new Map(expectedQuestions.map((question) => [question.key, question]));
  const existingQuestions = await prisma.questionnaireQuestion.findMany({
    where: { questionnaireId: questionnaire.id },
    select: { key: true, label: true, type: true, helpText: true, sortOrder: true, config: true },
  });
  const existingKeys = new Set(existingQuestions.map((question) => question.key));
  const hasCurrentShape = expectedKeys.length === existingKeys.size && expectedKeys.every((key) => existingKeys.has(key));

  const hasCurrentDefinition =
    hasCurrentShape &&
    existingQuestions.every((question) => {
      const expected = expectedByKey.get(question.key);
      if (!expected) {
        return false;
      }

      const existingConfig = question.config as { required?: boolean; options?: Array<{ label: string; value: string }> };
      const expectedConfig = expected.config as { required?: boolean; options?: Array<{ label: string; value: string }> };

      return (
        question.label === expected.label &&
        question.type === expected.type &&
        (question.helpText ?? null) === expected.helpText &&
        question.sortOrder === expected.sortOrder &&
        Boolean(existingConfig?.required) === Boolean(expectedConfig?.required) &&
        JSON.stringify(existingConfig?.options ?? []) === JSON.stringify(expectedConfig?.options ?? [])
      );
    });

  if (!hasCurrentDefinition) {
    await prisma.questionnaireQuestion.deleteMany({ where: { questionnaireId: questionnaire.id } });
    await prisma.questionnaireQuestion.createMany({ data: expectedQuestions });
  }

  return questionnaire;
}

export async function getPatientQuestionnaireContent() {
  if (!prisma) {
    return { source: "local" as const, questions: getLocalPatientQuestionContent() };
  }

  try {
    const questionnaire = await ensurePatientQuestionnaire();
    if (!questionnaire) {
      return { source: "local" as const, questions: getLocalPatientQuestionContent() };
    }

    const questions = await prisma.questionnaireQuestion.findMany({
      where: { questionnaireId: questionnaire.id },
      orderBy: { sortOrder: "asc" },
    });

    return {
      source: "database" as const,
      questions: questions.map((question) => {
        const config = question.config as { required?: boolean; options?: Array<{ label: string; value: string }> };

        return {
          id: question.key,
          label: question.label,
          type: question.type,
          helpText: question.helpText ?? undefined,
          required: Boolean(config.required),
          options: Array.isArray(config.options) ? config.options : undefined,
        };
      }),
    };
  } catch {
    return { source: "local" as const, questions: getLocalPatientQuestionContent() };
  }
}

export async function getSavedPatientQuestionnaire(input: { sessionId?: string; phone?: string }) {
  if (!prisma) {
    return null;
  }

  const phone = normalizePhone(input.phone);

  try {
    let submission = input.sessionId
      ? await prisma.questionnaireSubmission.findUnique({
          where: { sessionId: input.sessionId },
          include: { answers: true },
        })
      : null;

    if (!submission && phone) {
      submission = await prisma.questionnaireSubmission.findFirst({
        where: { patientPhone: phone },
        include: { answers: true },
        orderBy: { updatedAt: "desc" },
      });
    }

    if (!submission) {
      return null;
    }

    return {
      source: "database" as const,
      sessionId: submission.sessionId,
      answers: Object.fromEntries(
        submission.answers
          .filter((answer) => knownAnswerKeys.has(answer.key))
          .map((answer) => [answer.key, answer.value as PatientAnswerValue]),
      ),
      sectionIndex: submission.sectionIndex,
      questionIndex: submission.questionIndex,
      submitted: submission.status === "submitted",
      updatedAt: submission.updatedAt.toISOString(),
    };
  } catch {
    return null;
  }
}

async function upsertPatientUser(answers: Record<string, PatientAnswerValue>, sessionId: string) {
  if (!prisma) {
    throw new Error("Prisma unavailable");
  }

  const phone = normalizePhone(answers.phone) || normalizePhone(sessionId);
  const existingPatientRecord =
    phone.length >= 10
      ? await prisma.patientRecord.findUnique({
          where: { phone },
          select: { fullName: true, age: true, gender: true, region: true },
        })
      : null;
  const email = `patient-${phone || normalizeEmailPart(sessionId)}@spinexpert.local`;
  const fullName =
    String(answers.patientName ?? answers.fullName ?? existingPatientRecord?.fullName ?? "Patient").trim() ||
    "Patient";
  const profileAge = asNumber(answers.age) ?? existingPatientRecord?.age ?? null;
  const profileGender = asString(answers.gender) ?? existingPatientRecord?.gender ?? null;
  const profileRegion = asString(answers.region) ?? asString(answers.city) ?? existingPatientRecord?.region ?? null;

  const user = await prisma.user.upsert({
    where: { email },
    create: {
      email,
      passwordHash: `patient:${phone || sessionId}`,
      role: "patient",
      displayName: fullName,
      patientProfile: {
        create: {
          fullName,
          age: profileAge ?? 0,
          gender: profileGender ?? "not-provided",
          region: profileRegion ?? "not-provided",
          phone: phone || "not-provided",
          aadhar: String(answers.aadhar ?? "not-provided"),
        },
      },
    },
    update: {
      displayName: fullName,
      patientProfile: {
        upsert: {
          create: {
            fullName,
            age: profileAge ?? 0,
            gender: profileGender ?? "not-provided",
            region: profileRegion ?? "not-provided",
            phone: phone || "not-provided",
            aadhar: String(answers.aadhar ?? "not-provided"),
          },
          update: {
            fullName,
            phone: phone || "not-provided",
            ...(profileAge !== null ? { age: profileAge } : {}),
            ...(profileGender ? { gender: profileGender } : {}),
            ...(profileRegion ? { region: profileRegion } : {}),
          },
        },
      },
    },
  });

  return { user, phone };
}

async function resolveAssignedDoctorUser() {
  if (!prisma) {
    throw new Error("Prisma unavailable");
  }

  const existingDoctor = await prisma.doctorProfile.findFirst({
    include: { user: true },
    orderBy: { createdAt: "asc" },
  });

  if (existingDoctor) {
    return existingDoctor.user;
  }

  throw new Error("No doctor profile found. Please create at least one doctor account.");
}

export async function savePatientQuestionnaireToDatabase(record: PatientQuestionnairePayload) {
  const database = prisma;

  if (!database) {
    return { ok: true as const, storage: "local" as const, persisted: false };
  }

  const questionnaire = await ensurePatientQuestionnaire();
  if (!questionnaire) {
    return { ok: true as const, storage: "local" as const, persisted: false };
  }

  const explicitPhone = normalizePhone(record.patientPhone);
  const { user: patientUser, phone } = await upsertPatientUser({ ...record.answers, phone: explicitPhone || record.answers.phone }, record.sessionId);
  const resolvedPhone = explicitPhone || phone;
  if (resolvedPhone.length >= 10) {
    await ensurePatientRecordForPhone(resolvedPhone);
  }
  const doctorUser = await resolveAssignedDoctorUser();
  const status = record.submitted ? "submitted" : "draft";
  const bmi = calculateBmi(Number(record.answers.weightKg), Number(record.answers.heightCm));
  const activeSections = pickWorkflowSectionsForAnswers(record.answers);
  const visibleQuestions = getVisibleQuestions(activeSections, record.answers);
  const answeredCount = visibleQuestions.filter((question) => isFilled(record.answers[question.id])).length;
  const completionPct = Math.min(100, Math.round((answeredCount / Math.max(1, visibleQuestions.length)) * 100));
  const promAudit = buildPromAuditPayload(record.answers as Record<string, unknown>);

  async function saveOnce() {
    return database!.$transaction(async (tx) => {
      const existing = await tx.questionnaireSubmission.findUnique({
        where: { sessionId: record.sessionId },
        select: { id: true, appointmentId: true, createdAt: true },
      });

      const appointmentTimestamp = new Date();
      const appointmentTime = appointmentTimestamp.toLocaleTimeString("en-GB", {
        hour: "2-digit",
        minute: "2-digit",
        hour12: false,
      });

      const existingAppointmentRows = await tx.$queryRaw<Array<{ id: string }>>`
        SELECT id
        FROM "Appointment"
        WHERE "consultSessionId" = ${record.sessionId}
        LIMIT 1
      `;
      const existingAppointmentId = existingAppointmentRows[0]?.id;

      const profileFullName = asString(record.answers.patientName) || asString(record.answers.fullName) || patientUser.displayName;
      const profileAge = asNumber(record.answers.age);
      const profileGender = asString(record.answers.gender);
      const profileHeightCm = asNumber(record.answers.heightCm);
      const profileWeightKg = asNumber(record.answers.weightKg);
      const profileBmi = bmi ?? (profileHeightCm && profileWeightKg ? calculateBmi(profileWeightKg, profileHeightCm) : null);
      const profileRegion = asString(record.answers.region) || asString(record.answers.city);
      const profilePreferredLanguage = asString(record.answers.preferredLanguage);
      const profileDailyActivity = asString(record.answers.dailyActivity) || asString(record.answers.occupation) || asString(record.answers.activityLevel);
      const profileComorbidities = asStringArray(record.answers.comorbidities);
      const profileMedicalHistory = asStringArray(record.answers.medicalHistory);
      const profileCurrentMeds = asStringArray(record.answers.currentMeds);
      const profileCurrentMedicines = asString(record.answers.currentMedicines);
      const combinedMeds = [
        ...profileCurrentMeds,
        ...(profileCurrentMedicines ? [profileCurrentMedicines] : []),
      ];
      const profilePriorSurgery =
        Boolean(record.answers.priorSurgery) ||
        Boolean(record.answers.priorSpineSurgery);
      const profileSurgeryDetails = asString(record.answers.surgeryDetails) || asString(record.answers.spineSurgeryDetails);
      const profileEmail = asString(record.answers.email);

      const patientRecord =
        resolvedPhone.length >= 10
          ? await tx.patientRecord.upsert({
              where: { phone: resolvedPhone },
              create: {
                patientId: buildPatientId(),
                phone: resolvedPhone,
                email: profileEmail,
                fullName: profileFullName,
                age: profileAge ?? undefined,
                gender: profileGender ?? undefined,
                heightCm: profileHeightCm ?? undefined,
                weightKg: profileWeightKg ?? undefined,
                bmi: profileBmi ?? undefined,
                region: profileRegion ?? undefined,
                preferredLanguage: profilePreferredLanguage ?? undefined,
                dailyActivity: profileDailyActivity ?? undefined,
                comorbidities: profileComorbidities.length > 0 ? profileComorbidities : profileMedicalHistory,
                currentMeds: combinedMeds,
                priorSurgery: profilePriorSurgery,
                surgeryDetails: profileSurgeryDetails ?? undefined,
              },
              update: {
                email: profileEmail,
                fullName: profileFullName,
                age: profileAge ?? undefined,
                gender: profileGender ?? undefined,
                heightCm: profileHeightCm ?? undefined,
                weightKg: profileWeightKg ?? undefined,
                bmi: profileBmi ?? undefined,
                region: profileRegion ?? undefined,
                preferredLanguage: profilePreferredLanguage ?? undefined,
                dailyActivity: profileDailyActivity ?? undefined,
                comorbidities: profileComorbidities.length > 0 ? profileComorbidities : profileMedicalHistory,
                currentMeds: combinedMeds,
                priorSurgery: profilePriorSurgery,
                surgeryDetails: profileSurgeryDetails ?? undefined,
              },
              select: { id: true },
            })
          : null;

      const appointment = existing
        ? await tx.appointment.update({
            where: { id: existing.appointmentId },
            data: {
              patientName: patientUser.displayName,
              patientPhone: resolvedPhone || "",
              patientRecordId: patientRecord?.id ?? null,
              doctorName: doctorUser.displayName,
              appointmentDate: appointmentTimestamp,
              appointmentTime,
              appointmentType: "questionnaire",
              status: record.submitted ? "submitted" : "draft",
              createdBy: "patient",
              notes: `Patient questionnaire session: ${record.sessionId}`,
              updatedAt: new Date(),
            } as never,
          })
        : existingAppointmentId
          ? await tx.appointment.update({
              where: { id: existingAppointmentId },
              data: {
                patientId: patientUser.id,
                patientName: patientUser.displayName,
                patientPhone: resolvedPhone || "",
                patientRecordId: patientRecord?.id ?? null,
                doctorId: doctorUser.id,
                doctorName: doctorUser.displayName,
                appointmentDate: appointmentTimestamp,
                appointmentTime,
                appointmentType: "questionnaire",
                status: record.submitted ? "submitted" : "draft",
                createdBy: "patient",
                notes: `Patient questionnaire session: ${record.sessionId}`,
                updatedAt: new Date(),
              } as never,
            })
          : await tx.appointment.create({
              data: {
                consultSessionId: record.sessionId,
                patientId: patientUser.id,
                patientName: patientUser.displayName,
                patientPhone: resolvedPhone || "",
                patientRecordId: patientRecord?.id ?? null,
                doctorId: doctorUser.id,
                doctorName: doctorUser.displayName,
                appointmentDate: appointmentTimestamp,
                appointmentTime,
                appointmentType: "questionnaire",
                status: record.submitted ? "submitted" : "draft",
                createdBy: "patient",
                notes: `Patient questionnaire session: ${record.sessionId}`,
              } as never,
            });

      const now = new Date();
      const elapsedSeconds = existing
        ? Math.max(0, Math.round((now.getTime() - existing.createdAt.getTime()) / 1000))
        : 0;

      const submission = await tx.questionnaireSubmission.upsert({
        where: { sessionId: record.sessionId },
        create: {
          questionnaireId: questionnaire!.id,
          appointmentId: appointment.id,
          patientId: patientUser.id,
          patientRecordId: patientRecord?.id ?? null,
          doctorId: doctorUser.id,
          sessionId: record.sessionId,
          patientPhone: resolvedPhone || null,
          status,
          sectionIndex: record.sectionIndex,
          questionIndex: record.questionIndex,
          completionPct,
          durationSeconds: elapsedSeconds,
          bmi,
        },
        update: {
          patientRecordId: patientRecord?.id ?? null,
          patientPhone: resolvedPhone || null,
          status,
          sectionIndex: record.sectionIndex,
          questionIndex: record.questionIndex,
          completionPct,
          durationSeconds: elapsedSeconds,
          bmi,
        },
      });

      await tx.questionnaireAnswer.deleteMany({ where: { submissionId: submission.id } });
      await tx.questionnaireAnswer.createMany({
        data: [
          ...Object.entries(record.answers).map(([key, value]) => ({
            submissionId: submission.id,
            key,
            value: answerValue(value),
          })),
          {
            submissionId: submission.id,
            key: promAuditAnswerKeys.payload,
            value: answerValue(promAudit as unknown as PatientAnswerValue),
          },
          {
            submissionId: submission.id,
            key: promAuditAnswerKeys.instrument,
            value: answerValue(promAudit.instrument),
          },
          {
            submissionId: submission.id,
            key: promAuditAnswerKeys.percent,
            value: answerValue(promAudit.percent ?? ""),
          },
          {
            submissionId: submission.id,
            key: promAuditAnswerKeys.severity,
            value: answerValue(promAudit.severity),
          },
          {
            submissionId: submission.id,
            key: promAuditAnswerKeys.generatedAt,
            value: answerValue(promAudit.generatedAt),
          },
        ],
      });

      return submission;
    });
  }

  let saved;
  try {
    saved = await saveOnce();
  } catch (error) {
    const isUniqueConsultSession = error instanceof Prisma.PrismaClientKnownRequestError && error.code === "P2002" && String(error.meta?.target ?? "").includes("consultSessionId");

    if (!isUniqueConsultSession) {
      throw error;
    }

    saved = await saveOnce();
  }

  return { ok: true as const, storage: "database" as const, persisted: true, submissionId: saved.id };
}
